// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2024 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.3.20f1";
    extern const char* const UnityVersionDigits = "2022.3.20";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 20;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.3.20f1_61c2feb0970d";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.3.20f1_61c2feb0970d";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.3.20f1 (61c2feb0970d)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 6406910;

    extern const UInt64 UnityVersionDate = 1707733721;
    extern const char* const UnityVersionBranch = "2022.3/release";
    extern const char* const UnityVersionDisplay = "2022.3.20f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.3.20f1.git.6406910";
    extern const char* const UnityVersionRevision = "61c2feb0970d";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.3.20f1 (61c2feb0970d)";
    extern const wchar_t* const L_UnityVersion = L"2022.3.20f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2024 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 20
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.3.20f1_61c2feb0970d"
    #define UNITY_VERSION_PARENS_HASH "2022.3.20f1 (61c2feb0970d)"
    #define UNITY_VERSION_BLD 6406910
    #define UNITY_VERSION_WIN "2022.3.20.6406910"

#endif // !RC_INVOKED
